# https://help.github.com/en/articles/workflow-syntax-for-github-actions#name
name: Main

# Give it a try!
# curl -v -H "Accept: application/vnd.github.everest-preview+json" \
#  -H "Authorization: token $TOKEN" \
#   https://api.github.com/repos/:/dispatches \
#   -d '{"event_type":"update-dates-file"}'

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on: repository_dispatch

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobs
jobs:

  # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_id
  first_job:

    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
  
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
    
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables
    # https://github.com/actions/checkout
    - uses: actions/checkout@v1
    
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsid
    - name: Update dates.txt with new date

      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsenv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun
      run: |

        # ensure we're on the `master` branch.
        git checkout master
        
        # create or update `dates.txt`
        touch dates.txt
        
        # append the current datetime to the end of `dates.txt`
        echo `date` >> dates.txt
        
        # reveal what `dates.txt` looks like in the logs
        cat dates.txt
        
        # Git: set identity
        git config --global user.name "GITHUB_TOKEN"
        git config --global user.email "15894826+francisfuzz@users.noreply.github.com"
        
        # Git: set remote  
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
  
        # Git: add, commit, and push changes
        git add dates.txt
        git commit -m "github-actions: update dates.txt"
        GIT_TRACE=1 git push --verbose
